apiVersion: v1
kind: Namespace
metadata:
  name: adminer
  labels:
    name: adminer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adminer
  name: adminer
  namespace: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
      namespace: adminer
    spec:
      containers:
      - name: adminer
        image: adminer
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: adminer-svc
  namespace: adminer
spec:
  type: NodePort
  selector:
    app: adminer
  ports:
    - protocol: TCP
      nodePort: 30000
      port: 80
      targetPort: 8080