apiVersion: v1
kind: Namespace
metadata:
  name: taa
  labels:
    name: taa
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: taa-cfm
  namespace: taa
data:
  db_host: "taa-db.taa"
  db_user: "root"
  db_password: "12345678"
  db_name: "taskassign"