apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: taa-db
  namespace: taa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mysql
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: taa-cfm
                key: db_password
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: taa-db
  namespace: taa
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306